python inference.py \
    --output_dir=./saved_models_client1 \
    --model_type=roberta \
    --config_name=../../model/codebert-base/config.json \
    --model_name_or_path=../../model/codebert-base \
    --tokenizer_name=../../model/codebert-base \
    --do_test \
    --train_data_file=../dataset/train.jsonl \
    --eval_data_file=../dataset/valid.jsonl \
    --test_data_file=../dataset/test.jsonl \
    --epoch 2 \
    --block_size 256 \
    --train_batch_size 32 \
    --eval_batch_size 64 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1| tee test.log