python client.py \
    --output_dir=../saved_models_uneven_nums \
    --model_type=roberta \
    --config_name=../../model/codebert-base/config.json \
    --model_name_or_path=../../model/codebert-base \
    --tokenizer_name=../../model/codebert-base \
    --do_train \
    --train_data_dir=../nums/split_uneven \
    --eval_data_file=../dataset/valid.jsonl \
    --test_data_file=../dataset/test.jsonl \
    --epoch 1 \
    --block_size 400 \
    --train_batch_size 32 \
    --eval_batch_size 64 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training True\
    --type uneven_nums  2>&1 | tee train_uneven_nums.log