python inference_uneven_tags.py \
    --output_dir=./saved_models_uneven_tags \
    --model_type=roberta \
    --config_name=../../../model/codebert-base/config.json \
    --model_name_or_path=../../../model/codebert-base \
    --tokenizer_name=../../../model/codebert-base \
    --do_test \
    --train_data_file=../../dataset/train.txt \
    --eval_data_file=../../dataset/valid.txt \
    --test_data_file=../../dataset/valid.txt \
    --epoch 2 \
    --block_size 400 \
    --train_batch_size 16 \
    --eval_batch_size 32 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1| tee test_uneven_tags.log